// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	CaptchaId   string `json:"captcha_id,optional"`
	CaptchaCode string `json:"captcha_code,optional"`
	TotpCode    string `json:"totp_code"`
}

type LoginReply struct {
	Username   string `json:"username"`
	LoginToken string `json:"login_token"`
}

type CaptchaReply struct {
	CaptchaId string `json:"captcha_id"`
	Base64png string `json:"base64png"`
}

type GetAdminListRequest struct {
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

type GetAdminListResponse struct {
	Total int64   `json:"total"`
	List  []Admin `json:"list"`
}

type Admin struct {
	AdminId      int64  `json:"admin_id"`
	Username     string `json:"username"`
	Phone        string `json:"phone"`
	Email        string `json:"email"`
	EnableStatus int64  `json:"enable_status"`
	CreateTime   int64  `json:"create_time"`
	TotpSecret   string `json:"totp_secret"`
}

type AddAdminRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
}

type AddAdminResponse struct {
	AdminId int64 `json:"admin_id"`
}

type EnableAdminRequest struct {
	AdminId int64 `json:"admin_id"`
	Enable  int64 `json:"enable,default=1,options=1|2"`
}

type ResetAdminPwdRequest struct {
	LoginUserPwd string `json:"login_user_pwd"`
	AdminId      int64  `json:"admin_id"`
}

type ResetAdminTotpSecretRequest struct {
	AdminId int64 `json:"admin_id"`
}

type ResetAdminTotpSecretResponse struct {
	TotpSecret string `json:"totp_secret"`
}

type ModifyAdminPasswordRequest struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type GetPlatformBankCardListRequest struct {
	Search   string `form:"search,optional"`
	Currency string `form:"currency,optional"`
	Page     int64  `form:"page"`
	PageSize int64  `form:"page_size"`
}

type GetPlatformBankCardListResponse struct {
	Total int64                  `json:"total"`
	List  []PlatformBankCardList `json:"list"`
}

type PlatformBankCardList struct {
	CardId        int64  `json:"card_id"`
	BankName      string `json:"bank_name"`
	AccountName   string `json:"account_name"`
	CreateTime    int64  `json:"create_time"`
	CardNumber    string `json:"card_number"`
	BranchName    string `json:"branch_name"`
	Currency      string `json:"currency"`
	Status        int64  `json:"status"`
	MaxAmount     int64  `json:"max_amount"`
	Remark        string `json:"remark"`
	ReceivedToday int64  `json:"received_today"`
}

type GetPlatformBankCardRequest struct {
	CardId int64 `form:"card_id"`
}

type GetPlatformBankCardResponse struct {
	Card PlatformBankCard `json:"card"`
}

type PlatformBankCard struct {
	CardId      int64  `json:"card_id"`
	BankName    string `json:"bank_name"`
	AccountName string `json:"account_name"`
	CardNumber  string `json:"card_number"`
	BranchName  string `json:"branch_name"`
	Currency    string `json:"currency"`
	MaxAmount   int64  `json:"max_amount"`
	Remark      string `json:"remark"`
	QrCode      string `json:"qr_code"`
}

type AddPlatformBankCardRequest struct {
	BankName    string `json:"bank_name"`
	AccountName string `json:"account_name"`
	CardNumber  string `json:"card_number"`
	BranchName  string `json:"branch_name,optional"`
	Currency    string `json:"currency"`
	MaxAmount   int64  `json:"max_amount"`
	QrCode      string `json:"qr_code,optional"`
	Remark      string `json:"remark,optional"`
}

type ModifyPlatformBankCardRequest struct {
	CardId      int64  `json:"card_id"`
	BankName    string `json:"bank_name,optional"`
	AccountName string `json:"account_name,optional"`
	CardNumber  string `json:"card_number,optional"`
	BranchName  string `json:"branch_name"`
	Currency    string `json:"currency,optional"`
	MaxAmount   int64  `json:"max_amount,optional"`
	QrCode      string `json:"qr_code"`
	Remark      string `json:"remark"`
}

type EnablePlatformBankCardRequest struct {
	CardId int64 `json:"card_id"`
	Enable int64 `json:"enable,options=1|2"`
}

type DeletePlatformBankCardRequest struct {
	CardId int64 `json:"card_id"`
}

type AreaListReply struct {
	List []AreaData `json:"list"`
}

type AreaData struct {
	Id       int64  `json:"id"`
	AreaName string `json:"area_name"`
}

type AddUpstreamRequest struct {
	UpstreamName       string `json:"upstream_name"`
	CallConfig         string `json:"call_config,optional"`
	UpstreamMerchantNo string `json:"upstream_merchant_no"`
	UpstreamCode       string `json:"upstream_code"`
	AreaId             int64  `json:"area_id"`
}

type ModifyUpstreamRequest struct {
	UpstreamId         int64  `json:"upstream_id"`
	UpstreamName       string `json:"upstream_name,optional"`
	CallConfig         string `json:"call_config,optional"`
	UpstreamMerchantNo string `json:"upstream_merchant_no"`
	UpstreamCode       string `json:"upstream_code"`
	AreaId             int64  `json:"area_id"`
}

type GetUpstreamListRequest struct {
	UpstreamName string `form:"upstream_name,optional"`
	Page         int64  `form:"page"`
	PageSize     int64  `form:"page_size"`
}

type GetUpstreamListResponse struct {
	Total int64          `json:"total"`
	List  []UpstreamList `json:"list"`
}

type UpstreamList struct {
	UpstreamId         int64  `json:"upstream_id"`
	UpstreamName       string `json:"upstream_name"`
	CreateTime         int64  `json:"create_time"`
	UpstreamMerchantNo string `json:"upstream_merchant_no"`
	UpstreamCode       string `json:"upstream_code"`
	AreaName           string `json:"area_name"`
}

type GetUpstreamRequest struct {
	UpstreamId int64 `form:"upstream_id"`
}

type GetUpstreamResponse struct {
	Upstream Upstream `json:"upstream"`
}

type Upstream struct {
	UpstreamId         int64  `json:"upstream_id"`
	UpstreamName       string `json:"upstream_name"`
	CallConfig         string `json:"call_config"`
	CreateTime         int64  `json:"create_time"`
	UpstreamMerchantNo string `json:"upstream_merchant_no"`
	UpstreamCode       string `json:"upstream_code"`
	AreaId             int64  `json:"area_id"`
}

type GetUpstreamBalanceRequest struct {
	UpstreamId int64 `form:"upstream_id"`
}

type GetUpstreamBalanceResponse struct {
	List []UpstreamBalance `json:"list"`
}

type UpstreamBalance struct {
	Balance           float64 `json:"balance"`
	PayoutBalance     float64 `json:"payout_balance"`
	PayAmountLimit    float64 `json:"pay_amount_limit"`
	PayoutAmountLimit float64 `json:"payout_amount_limit"`
	IsDivideHundred   bool    `json:"is_divide_hundred"`
	Currency          string  `json:"currency"`
}

type AddUpstreamChannelRequest struct {
	ChannelName string `json:"channel_name"`
	ChannelCode string `json:"channel_code,optional"`
	ChannelDesc string `json:"channel_desc,optional"`
	Currency    string `json:"currency"`
	UpstreamId  int64  `json:"upstream_id"`
	ChannelType int64  `json:"channel_type,default=1,options=1|2"`
}

type ModifyUpstreamChannelRequest struct {
	ChannelId   int64  `json:"channel_id"`
	ChannelName string `json:"channel_name,optional"`
	ChannelCode string `json:"channel_code,optional"`
	ChannelDesc string `json:"channel_desc,optional"`
	Currency    string `json:"currency,optional"`
	UpstreamId  int64  `json:"upstream_id,optional"`
	ChannelType int64  `json:"channel_type,default=1,options=1|2"`
}

type GetUpstreamChannelListRequest struct {
	Search          string `form:"search,optional"`
	ChannelType     int64  `form:"channel_type,optional"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
}

type GetUpstreamChannelListResponse struct {
	Total int64                 `json:"total"`
	List  []UpstreamChannelList `json:"list"`
}

type UpstreamChannelList struct {
	ChannelId       int64   `json:"channel_id"`
	ChannelName     string  `json:"channel_name"`
	ChannelCode     string  `json:"channel_code"`
	ChannelDesc     string  `json:"channel_desc"`
	Currency        string  `json:"currency"`
	ChannelType     int64   `json:"channel_type"`
	UpstreamName    string  `json:"upstream_name"`
	Rate            float64 `json:"rate"`
	DeductionMethod int64   `json:"deduction_method"`
	Status          int64   `json:"status"`
	UpdateTime      int64   `json:"update_time"`
	SingleFee       int64   `json:"single_fee"`
}

type GetUpstreamChannelRequest struct {
	ChannelId int64 `form:"channel_id"`
}

type GetUpstreamChannelResponse struct {
	Channel UpstreamChannel `json:"channel"`
}

type UpstreamChannel struct {
	ChannelId    int64  `json:"channel_id"`
	ChannelName  string `json:"channel_name"`
	ChannelCode  string `json:"channel_code"`
	ChannelDesc  string `json:"channel_desc"`
	Currency     string `json:"currency"`
	UpstreamId   int64  `json:"upstream_id"`
	UpstreamName string `json:"upstream_name"`
	ChannelType  int64  `json:"channel_type"`
}

type GetUpstreamChannelConfigRequest struct {
	ChannelId int64 `form:"channel_id"`
}

type GetUpstreamChannelConfigResponse struct {
	ChannelConfig UpstreamChannelConfig `json:"channel_config"`
}

type UpstreamChannelConfig struct {
	ChannelId       int64   `json:"channel_id"`
	DeductionMethod int64   `json:"deduction_method"`
	Rate            float64 `json:"rate"`
	SingleFee       int64   `json:"single_fee"`
	SingleMaxAmount int64   `json:"single_max_amount"`
}

type SaveUpstreamChannelConfigRequest struct {
	ChannelId       int64   `json:"channel_id"`
	DeductionMethod int64   `json:"deduction_method,default=1,options=1|2"` // 扣费方式: 1-内扣， 2-外扣
	Rate            float64 `json:"rate,default=0,range=[0:100]"`
	SingleFee       int64   `json:"single_fee,default=0"`
	SingleMaxAmount int64   `json:"single_max_amount,default=0"`
}

type EnableUpstreamChannelRequest struct {
	ChannelId int64 `json:"channel_id"`
	Enable    int64 `json:"enable,default=1,options=1|2"`
}

type DeleteUpstreamChannelRequest struct {
	ChannelId int64 `json:"channel_id"`
}

type GetPlatformChannelListRequest struct {
	Search   string `form:"search,optional"`
	Page     int64  `form:"page"`
	PageSize int64  `form:"page_size"`
}

type GetPlatformChannelListResponse struct {
	Total int64                 `json:"total"`
	List  []PlatformChannelList `json:"list"`
}

type PlatformChannelList struct {
	ChannelId           int64  `json:"channel_id"`
	ChannelName         string `json:"channel_name"`
	ChannelCode         string `json:"channel_code"`
	ChannelDesc         string `json:"channel_desc"`
	ChannelType         int64  `json:"channel_type"`
	Status              int64  `json:"status"`
	CreateTime          int64  `json:"create_time"`
	UpdateTime          int64  `json:"update_time"`
	UpstreamChannelName string `json:"upstream_channel_name"`
	AreaId              int64  `json:"area_id"`
	AreaName            string `json:"area_name"`
}

type AddPlatformChannelRequest struct {
	ChannelName string `json:"channel_name"`
	ChannelCode string `json:"channel_code"`
	ChannelDesc string `json:"channel_desc,optional"`
	ChannelType int64  `json:"channel_type,default=1,options=1|2"`
	AreaId      int64  `json:"area_id"`
}

type ModifyPlatformChannelRequest struct {
	ChannelId   int64  `json:"channel_id"`
	ChannelName string `json:"channel_name,optional"`
	ChannelCode string `json:"channel_code,optional"`
	ChannelDesc string `json:"channel_desc,optional"`
	ChannelType int64  `json:"channel_type,default=1,options=1|2"`
	AreaId      int64  `json:"area_id"`
}

type EnablePlatformChannelRequest struct {
	ChannelId int64 `json:"channel_id"`
	Enable    int64 `json:"enable,default=1,options=1|2"`
}

type DeletePlatformChannelRequest struct {
	ChannelId int64 `json:"channel_id"`
}

type GetPlatformUpstreamListRequest struct {
	ChannelId int64 `form:"channel_id"`
}

type GetPlatformUpstreamListResponse struct {
	ChannelId        int64                     `json:"channel_id"`
	LinkedChannel    []PlatformUpstreamChannel `json:"linked_channel"`
	NotLinkedChannel []PlatformUpstreamChannel `json:"not_linked_channel"`
}

type PlatformUpstreamChannel struct {
	UpstreamChannelId   int64  `json:"upstream_channel_id"`
	UpstreamChannelName string `json:"upstream_channel_name"`
}

type SavePlatformUpstreamRequest struct {
	ChannelId          int64   `json:"channel_id"`
	UpstreamChannelIds []int64 `json:"upstream_channel_ids,optional"`
}

type PlatformWalletLogListRequest struct {
	BusinessNo string `form:"business_no,optional"`
	Source     int64  `form:"source,optional"`
	Currency   string `form:"currency,optional"`
	Page       int64  `form:"page"`
	PageSize   int64  `form:"page_size"`
}

type PlatformWalletLogListReply struct {
	Total int64                       `json:"total"`
	List  []PlatformWalletLogListData `json:"list"`
}

type PlatformWalletLogListData struct {
	Id          int64  `json:"id"`           //平台钱包日志id
	BusinessNo  string `json:"business_no"`  //业务号
	Source      int64  `json:"source"`       //收益来源:3-商户提现；4-商户代付；5-商户代收；
	MerchantFee int64  `json:"merchant_fee"` //商户手续费
	UpstreamFee int64  `json:"upstream_fee"` //上游手续费
	Income      int64  `json:"income"`       //收益
	CreateTime  int64  `json:"create_time"`  //创建时间
	Currency    string `json:"currency"`     //币种
}

type PlanformChannelSettingRequest struct {
	ChannelId   int64 `json:"channel_id"`
	StartTime   int64 `json:"start_time"`
	EndTime     int64 `json:"end_time"`
	StartAmount int64 `json:"start_amount"`
	EndAmount   int64 `json:"end_amount"`
}

type PlanformChannelSettingReply struct {
}

type GetPlanformChannelSettingRequest struct {
	ChannelId int64 `form:"channel_id"`
}

type GetPlanformChannelSettingReply struct {
	StartTime   int64 `json:"start_time"`
	EndTime     int64 `json:"end_time"`
	StartAmount int64 `json:"start_amount"`
	EndAmount   int64 `json:"end_amount"`
}

type AddMerchantRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Currency string `json:"currency"`
	AreaId   int64  `json:"area_id"`
}

type AddMerchantResponse struct {
	MerchantId int64 `json:"merchant_id"`
}

type ModifyMerchantRequest struct {
	MerchantId int64  `json:"merchant_id"`
	Phone      string `json:"phone"`
	Email      string `json:"email"`
}

type GetMerchantListRequest struct {
	Username        string `form:"username,optional"`
	ContactDetails  string `form:"contact_details,optional"`
	Currency        string `form:"currency,optional"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
}

type GetMerchantListResponse struct {
	Total int64      `json:"total"`
	List  []Merchant `json:"list"`
}

type Merchant struct {
	MerchantId   int64  `json:"merchant_id"`
	MerchantNo   string `json:"merchant_no"`
	Username     string `json:"username"`
	Phone        string `json:"phone"`
	Email        string `json:"email"`
	Currency     string `json:"currency"`
	CreateTime   int64  `json:"create_time"`
	Status       int64  `json:"status"`
	Balance      int64  `json:"balance"`
	IpWhiteList  string `json:"ip_white_list"`
	TotpSecret   string `json:"totp_secret"`
	AreaName     string `json:"area_name"`
	FrozenAmount int64  `json:"frozen_amount"`
}

type ResetMerchantPwdRequest struct {
	LoginUserPwd string `json:"login_user_pwd"`
	MerchantId   int64  `json:"merchant_id"`
}

type UpdateMerchantPwdRequest struct {
	LoginUserPwd string `json:"login_user_pwd"`
	MerchantId   int64  `json:"merchant_id"`
	Password     string `json:"password"`
}

type ModifyMerchantPayPwdRequest struct {
	MerchantId   int64  `json:"merchant_id"`
	LoginUserPwd string `json:"login_user_pwd"`
	PayPassword  string `json:"pay_password"`
}

type ResetMerchantTotpSecretRequest struct {
	MerchantId int64 `json:"merchant_id"`
}

type ResetMerchantTotpSecretResponse struct {
	TotpSecret string `json:"totp_secret"`
}

type EnableMerchantRequest struct {
	MerchantId int64 `json:"merchant_id"`
	Enable     int64 `json:"enable,default=1,options=1|2"`
}

type ModifyMerchantBalanceRequest struct {
	MerchantId   int64  `json:"merchant_id"`
	OpType       int64  `json:"op_type,default=1,options=1|2"`
	ChangeAmount int64  `json:"change_amount"`
	Remark       string `json:"remark,optional"`
}

type GetMerchantBankCardListRequest struct {
	Search   string `form:"search,optional"`
	Page     int64  `form:"page"`
	PageSize int64  `form:"page_size"`
}

type GetMerchantBankCardListResponse struct {
	Total int64              `json:"total"`
	List  []MerchantBankCard `json:"list"`
}

type MerchantBankCard struct {
	CardId      int64  `json:"card_id"`
	Username    string `json:"username"`
	BankName    string `json:"bank_name"`
	AccountName string `json:"account_name"`
	CardNumber  string `json:"card_number"`
	BranchName  string `json:"branch_name"`
	Currency    string `json:"currency"`
	Remark      string `json:"remark"`
	CreateTime  int64  `json:"create_time"`
	UpdateTime  int64  `json:"update_time"`
}

type GetPlatformChannelNameListRequest struct {
	MerchantId  int64 `form:"merchant_id,optional"`
	Status      int64 `form:"status,optional"`
	ChannelType int64 `form:"channel_type,optional"`
}

type GetPlatformChannelNameListResponse struct {
	List []PlatformChannelNameList `json:"list"`
}

type PlatformChannelNameList struct {
	ChannelId   int64  `json:"channel_id"`
	ChannelName string `json:"channel_name"`
	ChannelType int64  `json:"channel_type"`
}

type AddMerchantChannelRequest struct {
	MerchantId int64 `json:"merchant_id"`
	ChannelId  int64 `json:"channel_id"`
}

type GetMerchantChannelListRequest struct {
	MerchantId int64 `form:"merchant_id"`
}

type GetMerchantChannelListResponse struct {
	Total int64                 `json:"total"`
	List  []MerchantChannelList `json:"list"`
}

type MerchantChannelList struct {
	ChannelId             int64    `json:"channel_id"`
	MerchantId            int64    `json:"merchant_id"`
	ChannelRate           float64  `json:"channel_rate"`
	SingleFee             int64    `json:"single_fee"`
	Status                int64    `json:"status"`
	PlatformChannelName   string   `json:"platform_channel_name"`
	PlatformChannelType   int64    `json:"platform_channel_type"`
	UpstreamChannelWeight []string `json:"upstream_channel_weight"`
}

type ModifyMerchantChannelRateRequest struct {
	ChannelId   int64   `json:"channel_id"`
	ChannelRate float64 `json:"channel_rate,range=[0:100]"`
	SingleFee   int64   `json:"single_fee"`
}

type EnableMerchantChannelRequest struct {
	ChannelId int64 `json:"channel_id"`
	Enable    int64 `json:"enable,default=1,options=1|2"`
}

type DeleteMerchantChannelRequest struct {
	ChannelId int64 `json:"channel_id"`
}

type GetMerchantChannelUpstreamListRequest struct {
	Page       int64 `form:"page"`
	PageSize   int64 `form:"page_size"`
	MerchantId int64 `form:"merchant_id"`
	ChannelId  int64 `form:"channel_id"`
}

type GetMerchantChannelUpstreamListResponse struct {
	Total int64                         `json:"total"`
	List  []MerchantChannelUpstreamList `json:"list"`
}

type MerchantChannelUpstreamList struct {
	Id                    int64  `json:"id"`
	UpstreamChannelName   string `json:"upstream_channel_name"`
	UpstreamChannelWeight int64  `json:"upstream_channel_weight"`
}

type SaveMerchantChannelUpstreamRequest struct {
	Id                    int64 `json:"id"`
	UpstreamChannelWeight int64 `json:"upstream_channel_weight,default=0,range=[0:1000]"`
}

type GetMerchantWithdrawConfigRequest struct {
	MerchantId int64 `form:"merchant_id"`
}

type GetMerchantWithdrawConfigResponse struct {
	Config MerchantWithdrawConfig `json:"config"`
}

type MerchantWithdrawConfig struct {
	ConfigId        int64   `json:"config_id"`
	SingleMinAmount int64   `json:"single_min_amount"`
	SingleMaxAmount int64   `json:"single_max_amount"`
	DeductionMethod int64   `json:"deduction_method"`
	WithdrawRate    float64 `json:"withdraw_rate"`
	SingleFee       int64   `json:"single_fee"`
}

type AddMerchantWithdrawConfigRequest struct {
	MerchantId      int64   `json:"merchant_id"`
	SingleMinAmount int64   `json:"single_min_amount"`
	SingleMaxAmount int64   `json:"single_max_amount"`
	WithdrawRate    float64 `json:"withdraw_rate,optional,range=[0:100]"`
	SingleFee       int64   `json:"single_fee,optional"`
}

type AddMerchantWithdrawConfigResponse struct {
	ConfigId int64 `json:"config_id"`
}

type ModifyMerchantWithdrawConfigRequest struct {
	ConfigId        int64   `json:"config_id"`
	SingleMinAmount int64   `json:"single_min_amount"`
	SingleMaxAmount int64   `json:"single_max_amount"`
	WithdrawRate    float64 `json:"withdraw_rate,range=[0:100]"`
	SingleFee       int64   `json:"single_fee"`
}

type GetMerchantWalletLogListRequest struct {
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
	SerialNo        int64  `form:"serial_no,optional"`
	BusinessNo      string `form:"business_no,optional"`
	MerchantAccount string `form:"merchant_account,optional"`
	OpType          int64  `form:"op_type,optional"`
	OrderType       int64  `form:"order_type,optional"`
	Currency        string `form:"currency,optional"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	IdOrBusinessNo  string `form:"id_or_business_no,optional"`
}

type GetMerchantWalletLogListResponse struct {
	Total int64                   `json:"total"`
	List  []MerchantWalletLogList `json:"list"`
}

type MerchantWalletLogList struct {
	SerialNo           int64  `json:"serial_no"`
	BusinessNo         string `json:"business_no"`
	MerchantAccount    string `json:"merchant_account"`
	Currency           string `json:"currency"`
	ChangeAmount       int64  `json:"change_amount"`
	ChangeAfterBalance int64  `json:"change_after_balance"`
	OpType             int64  `json:"op_type"`
	OrderType          int64  `json:"order_type"`
	Remark             string `json:"remark"`
	CreateTime         int64  `json:"createTime"`
}

type UpdateMerchantIpWhitelistRequest struct {
	MerchantId  int64  `json:"merchant_id"`
	IpWhitelist string `json:"ip_white"`
}

type GetPayOrderListRequest struct {
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
	OrderNo         string `form:"order_no,optional"`
	MerchantOrderNo string `form:"merchant_order_no,optional"`
	UpstreamOrderNo string `form:"upstream_order_no,optional"`
	MerchantName    string `form:"merchant_name,optional"`
	Currency        string `form:"currency,optional"`
	ChannelId       int64  `form:"channel_id,optional"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
	OrderType       string `form:"order_type,optional"`
}

type GetPayOrderListResponse struct {
	Total int64          `json:"total"`
	List  []PayOrderList `json:"list"`
}

type PayOrderList struct {
	OrderNo         string `json:"order_no"`
	MerchantOrderNo string `json:"merchant_order_no"`
	UpstreamOrderNo string `json:"upstream_order_no"`
	MerchantName    string `json:"merchant_name"`
	Currency        string `json:"currency"`
	OrderAmount     int64  `json:"order_amount"`
	MerchantFee     int64  `json:"merchant_fee"`
	IncreaseAmount  int64  `json:"increase_amount"`
	UpstreamName    string `json:"upstream_name"`
	ChannelName     string `json:"channel_name"`
	OrderStatus     int64  `json:"order_status"`
	CreateTime      int64  `json:"create_time"`
	UpdateTime      int64  `json:"update_time"`
	OrderType       string `json:"order_type"`
	PaymentAmount   int64  `json:"payment_amount"` // 用户实际支付金额
}

type GetPayOrderDetailRequest struct {
	OrderNo string `form:"order_no"`
}

type GetPayOrderDetailResponse struct {
	Data PayOrderDetail `json:"data"`
}

type PayOrderDetail struct {
	OrderNo             string `json:"order_no"` //平台订单号
	MerchantOrderNo     string `json:"merchant_order_no"`
	UpstreamOrderNo     string `json:"upstream_order_no"`
	MerchantName        string `json:"merchant_name"`
	MerchantNo          string `json:"merchant_no"`
	ReqAmount           int64  `json:"req_amount"`      //请求上游的金额
	IncreaseAmount      int64  `json:"increase_amount"` //账户增加的金额
	MerchantFee         int64  `json:"merchant_fee"`    //商户手续费
	UpstreamFee         int64  `json:"upstream_fee"`    //上游手续费
	OrderStatus         int64  `json:"order_status"`    //订单状态:1-待支付;2-已支付;3-超时
	Currency            string `json:"currency"`
	CreateTime          int64  `json:"create_time"`
	UpdateTime          int64  `json:"update_time"`
	NotifyUrl           string `json:"notify_url"`            //异步通知url
	ReturnUrl           string `json:"return_url"`            //同步跳转url
	PlatformChannelId   int64  `json:"platform_channel_id"`   //平台通道id
	UpstreamChannelId   int64  `json:"upstream_channel_id"`   //上游通道id
	NotifyStatus        int64  `json:"notify_status"`         //	异步通知状态(0未通知,1成功,2通知进行中,3超时)
	Subject             string `json:"subject"`               //商品的标题/交易标题/订单标题/订单关键字等
	PlatformChannelName string `json:"platform_channel_name"` //平台通道名称
	UpstreamChannelName string `json:"upstream_channel_name"` //上游通道名称
	PaymentAmount       int64  `json:"payment_amount"`        // 用户实际支付金额
}

type GetTransferOrderListRequest struct {
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	OrderNo         string `form:"order_no,optional"`
	MerchantOrderNo string `form:"merchant_order_no,optional"`
	UpstreamOrderNo string `form:"upstream_order_no,optional"`
	MerchantName    string `form:"merchant_name,optional"`
	Currency        string `form:"currency,optional"`
	ChannelId       int64  `form:"channel_id,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
	OrderType       string `form:"order_type,optional"`
}

type GetTransferOrderListResponse struct {
	Total int64               `json:"total"`
	List  []TransferOrderList `json:"list"`
}

type TransferOrderList struct {
	OrderNo         string `json:"order_no"`
	MerchantOrderNo string `json:"merchant_order_no"`
	UpstreamOrderNo string `json:"upstream_order_no"`
	MerchantName    string `json:"merchant_name"`
	Currency        string `json:"currency"`
	OrderAmount     int64  `json:"order_amount"`
	MerchantFee     int64  `json:"merchant_fee"`
	PayeeRealAmount int64  `json:"payee_real_amount"`
	UpstreamName    string `json:"upstream_name"`
	ChannelName     string `json:"channel_name"`
	OrderStatus     int64  `json:"order_status"`
	CreateTime      int64  `json:"create_time"`
	UpdateTime      int64  `json:"update_time"`
	OrderSource     int64  `json:"order_source"`
	OrderType       string `json:"order_type"`
}

type GetTransferOrderDetailRequest struct {
	OrderNo string `form:"order_no"`
}

type GetTransferOrderDetailResponse struct {
	Data TransferOrderDetail `json:"data"`
}

type TransferOrderDetail struct {
	OrderNo         string `json:"order_no"`
	MerchantOrderNo string `json:"merchant_order_no"`
	UpstreamOrderNo string `json:"upstream_order_no"`
	MerchantName    string `json:"merchant_name"`
	MerchantNo      string `json:"merchant_no"`
	ReqAmount       int64  `json:"req_amount"`        //订单请求金额
	DecreaseAmount  int64  `json:"decrease_amount"`   //账户扣除的金额
	MerchantFee     int64  `json:"merchant_fee"`      //	商户手续费
	UpstreamFee     int64  `json:"upstream_fee"`      //上游手续费
	PayeeRealAmount int64  `json:"payee_real_amount"` //收款方实际到账金额
	FeeDeductType   int64  `json:"fee_deduct_type"`   //手续费扣款方式(1内扣,2外扣)
	UpstreamAmount  int64  `json:"upstream_amount"`   //请求上游的金额
	Currency        string `json:"Currency"`
	CreateTime      int64  `json:"CreateTime"`
	UpdateTime      int64  `json:"UpdateTime"`
	NotifyUrl       string `json:"notify_url"`    //	异步通知地址
	BankName        string `json:"bank_name"`     //	收款银行名称
	CardNumber      string `json:"card_number"`   //	收款卡号
	AccountName     string `json:"account_name"`  //	银行卡开户名
	BranchName      string `json:"branch_name"`   //支行名称
	NotifyStatus    int64  `json:"notify_status"` //	异步通知状态(0未通知,1成功,2通知进行中,3超时)
	OrderSource     int64  `json:"order_source"`
}

type GetMerchantRechargeOrderListRequest struct {
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
	OrderNo         string `form:"order_no,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
	MerchantName    string `form:"merchant_name,optional"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
}

type GetMerchantRechargeOrderListResponse struct {
	Total int64                       `json:"total"`
	List  []MerchantRechargeOrderList `json:"list"`
}

type MerchantRechargeOrderList struct {
	OrderNo        string `json:"order_no"`
	MerchantName   string `json:"merchant_name"`
	OrderAmount    int64  `json:"order_amount"`
	RechargeRemark string `json:"recharge_remark"`
	BankName       string `json:"bank_name"`
	PayeeName      string `json:"payee_name"`
	CardNumber     string `json:"card_number"`
	OrderStatus    int64  `json:"order_status"`
	DealWithRemark string `json:"deal_with_remark"`
	CreateTime     int64  `json:"create_time"`
	FinishTime     int64  `json:"finish_time"`
	Currency       string `json:"currency"`
}

type MerchantRechargeOrderAuditRequest struct {
	OrderNo        string `json:"order_no"`
	OrderStatus    int64  `json:"order_status"`
	DealWithRemark string `json:"deal_with_remark,optional"`
}

type GetMerchantWithdrawOrderListRequest struct {
	Page            int64  `form:"page,default=1"`
	PageSize        int64  `form:"page_size,default=10"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	MerchantName    string `form:"merchant_name,optional"`
	OrderNo         string `form:"order_no,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
}

type GetMerchantWithdrawOrderListResponse struct {
	Total int64                       `json:"total"`
	List  []MerchantWithdrawOrderList `json:"list"`
}

type MerchantWithdrawOrderList struct {
	OrderNo             string `json:"order_no"`
	MerchantName        string `json:"merchant_name"`
	OrderAmount         int64  `json:"order_amount"`
	MerchantFee         int64  `json:"merchant_fee"`
	RealAmount          int64  `json:"real_amount"`
	Remark              string `json:"remark"`
	BankName            string `json:"bank_name"`
	PayeeName           string `json:"payee_name"`
	CardNumber          string `json:"card_number"`
	BranchName          string `json:"branch_name"`
	AuditRemark         string `json:"audit_remark"`
	CreateTime          int64  `json:"create_time"`
	AuditTime           int64  `json:"audit_time"`
	OrderStatus         int64  `json:"order_status"`
	UpstreamOrderNo     string `json:"upstream_order_no"`
	UpstreamChannelName string `json:"upstream_channel_name"`
	Currency            string `json:"currency"`
	DeductionMethod     int64  `json:"deduction_method"`
}

type MerchantWithdrawOrderAuditRequest struct {
	OrderNo     string `json:"order_no"`
	AuditStatus int64  `json:"audit_status"`
	AuditRemark string `json:"audit_remark,optional"`
}

type MerchantWithdrawSuccessRequest struct {
	OrderNo string `json:"order_no"`
	Remark  string `json:"remark,optional"`
}

type UpTransferChannelListRequest struct {
	Currency        string `form:"currency"`
	DeductionMethod string `form:"deduction_method"`
}

type UpTransferChannelListResponse struct {
	List []UpTransferChannel `json:"list"`
}

type UpTransferChannel struct {
	ChannelId   int64  `json:"channel_id"`
	ChannelName string `json:"channel_name"`
	ChannelCode string `json:"channel_code"`
}

type WithdrawOrderAllotRequest struct {
	OrderNo string `json:"order_no"`
}

type WithdrawOrderAllotResponse struct {
}

type PayOrderNotifyRequest struct {
	OrderNo string `json:"order_no"`
}

type PayOrderNotifyResponse struct {
	NotifyResponse string `json:"notify_response"`
}

type TransferOrderNotifyRequest struct {
	OrderNo string `json:"order_no"`
}

type TransferOrderNotifyResponse struct {
	NotifyResponse string `json:"notify_response"`
}

type ModifyPayTestOrderStatusRequest struct {
	OrderNo     string `json:"order_no"`
	OrderStatus int64  `json:"order_status"`
}

type ModifyTransferTestOrderStatusRequest struct {
	OrderNo     string `json:"order_no"`
	OrderStatus int64  `json:"order_status"`
}

type LogoutResponse struct {
}

type UploadImageRequest struct {
	ImageStr string `json:"image_str"`
}

type UploadImageResponse struct {
	ImageUrl string `json:"image_url"`
}

type GetCurrencyListResponse struct {
	List []Currency `json:"list"`
}

type Currency struct {
	Currency        string `json:"currency"`
	Symbol          string `json:"symbol"`
	Country         string `json:"country"`
	IsDivideHundred int64  `json:"is_divide_hundred"`
}

type SaveSiteConfigRequest struct {
	SiteName string `json:"site_name"`
	SiteLogo string `json:"site_logo"`
	SiteLang string `json:"site_lang"`
}

type GetSiteConfigResponse struct {
	SiteName string `json:"site_name"`
	SiteLogo string `json:"site_logo"`
	SiteLang string `json:"site_lang"`
}

type GetOtherConfigResponse struct {
	PayTradeTypeSlice      string `json:"pay_trade_type_slice"`      //代收交易方式
	TransferTradeTypeSlice string `json:"transfer_trade_type_slice"` //代付交易类型
}

type SaveOtherConfigRequest struct {
	PayTradeTypeSlice      string `json:"pay_trade_type_slice"`      //代收交易方式
	TransferTradeTypeSlice string `json:"transfer_trade_type_slice"` //代付交易类型
}

type PayOrderExportRequest struct {
	OrderNo         string `form:"order_no,optional"`
	MerchantOrderNo string `form:"merchant_order_no,optional"`
	UpstreamOrderNo string `form:"upstream_order_no,optional"`
	MerchantName    string `form:"merchant_name,optional"`
	Currency        string `form:"currency"`
	ChannelId       int64  `form:"channel_id,optional"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
}

type PayOrderExportResponse struct {
	Total               int64                `json:"total"`
	TotalReqAmount      int64                `json:"total_req_amount"`
	TotalPayAmount      int64                `json:"total_pay_amount"`
	TotalFee            int64                `json:"total_fee"`
	TotalIncreaseAmount int64                `json:"total_increase_amount"`
	IsDivideHundred     bool                 `json:"is_divide_hundred"`
	List                []PayOrderExportData `json:"list"`
}

type PayOrderExportData struct {
	Id              int64   `json:"id"`
	MerchantName    string  `json:"merchant_name"`
	OrderNo         string  `json:"order_no"`
	MerchantOrderNo string  `json:"merchant_order_no"`
	ReqAmount       int64   `json:"req_amount"`
	PaymentAmount   int64   `json:"payment_amount"`
	Rate            float64 `json:"rate"`
	SingleFee       int64   `json:"single_fee"`
	Fee             int64   `json:"fee"`
	IncreaseAmount  int64   `json:"increase_amount"`
	ChannelName     string  `json:"channel_name"`
	OrderStatus     string  `json:"order_status"`
	CreateTime      int64   `json:"create_time"`
	UpdateTime      int64   `json:"update_time"`
}

type TransferOrderExportRequest struct {
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	OrderNo         string `form:"order_no,optional"`
	MerchantOrderNo string `form:"merchant_order_no,optional"`
	UpstreamOrderNo string `form:"upstream_order_no,optional"`
	MerchantName    string `form:"merchant_name,optional"`
	Currency        string `form:"currency"`
	ChannelId       int64  `form:"channel_id,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
}

type TransferOrderExportResponse struct {
	Total               int64                     `json:"total"`
	TotalReqAmount      int64                     `json:"total_req_amount"`
	TotalFee            int64                     `json:"total_fee"`
	TotalIncreaseAmount int64                     `json:"total_increase_amount"`
	IsDivideHundred     bool                      `json:"is_divide_hundred"`
	List                []TransferOrderExportData `json:"list"`
}

type TransferOrderExportData struct {
	Id              int64   `json:"id"`
	MerchantName    string  `json:"merchant_name"`
	OrderNo         string  `json:"order_no"`
	MerchantOrderNo string  `json:"merchant_order_no"`
	ReqAmount       int64   `json:"req_amount"`
	Rate            float64 `json:"rate"`
	SingleFee       int64   `json:"single_fee"`
	Fee             int64   `json:"fee"`
	IncreaseAmount  int64   `json:"increase_amount"`
	ChannelName     string  `json:"channel_name"`
	OrderStatus     string  `json:"order_status"`
	CreateTime      int64   `json:"create_time"`
	UpdateTime      int64   `json:"update_time"`
}

type WalletLogExportRequest struct {
	SerialNo        int64  `form:"serial_no,optional"`
	BusinessNo      string `form:"business_no,optional"`
	MerchantAccount string `form:"merchant_account,optional"`
	OpType          int64  `form:"op_type,optional"`
	OrderType       int64  `form:"order_type,optional"`
	Currency        string `form:"currency"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	IdOrBusinessNo  string `form:"id_or_business_no,optional"`
}

type WalletLogExportResponse struct {
	Total           int64                 `json:"total"`
	IsDivideHundred bool                  `json:"is_divide_hundred"`
	List            []WalletLogExportData `json:"list"`
}

type WalletLogExportData struct {
	Id           int64  `json:"id"`
	BusinessNo   string `json:"business_no"`   //业务单号:(充值；提现；代付；收款)
	ChangeAmount int64  `json:"change_amount"` //变动金额
	AfterBalance int64  `json:"after_balance"` //变动后余额
	OpType       string `json:"op_type"`       //变动类型：1+，2-
	OrderType    string `json:"order_type"`    //变动来源：1-手动调账；2-充值；3-提现；4-代付；5-收款；
	Remark       string `json:"remark"`        //备注
	CreateTime   int64  `json:"create_time"`   //创建时间
}
