// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	CaptchaId   string `json:"captcha_id,optional"`
	CaptchaCode string `json:"captcha_code,optional"`
	TotpCode    string `json:"totp_code"`
}

type LoginReply struct {
	Username     string       `json:"username"`
	LoginToken   string       `json:"login_token"`
	CurrencyData CurrencyData `json:"currency_data"`
}

type CurrencyData struct {
	Currency        string `json:"currency"`
	Symbol          string `json:"symbol"`
	IsDivideHundred int64  `json:"is_divide_hundred"`
}

type CaptchaReply struct {
	CaptchaId string `json:"captcha_id"`
	Base64png string `json:"base64png"`
}

type LogoutResponse struct {
}

type GetBaseInfoResponse struct {
	Data BaseInfoData `json:"data"`
}

type BaseInfoData struct {
	Username   string `json:"username"`
	MerchantId int64  `json:"merchant_id"`
	Phone      string `json:"phone"`
	Email      string `json:"email"`
	Md5Key     string `json:"md5_key"`
	MerchantNo string `json:"merchant_no"`
}

type Md5KeyResponse struct {
	Md5Key string `json:"md5_key"`
}

type UpdateBaseInfoReq struct {
	Phone string `json:"phone"`
	Email string `json:"email"`
}

type UpdateLoginPassWordReq struct {
	OldPwd string `json:"old_password"`
	NewPwd string `json:"new_password"`
}

type UpdatePayPassWordReq struct {
	OldPayPwd string `json:"old_pay_pwd"`
	NewPayPwd string `json:"new_pay_pwd"`
}

type GetChannelListReq struct {
	ChannelType int64 `form:"channel_type,optional"`
}

type GetChannelListResponse struct {
	Total int64         `json:"total"`
	List  []ChannelList `json:"list"`
}

type ChannelList struct {
	ChannelId   int64   `json:"channel_id"`
	ChannelName string  `json:"channel_name"`
	ChannelCode string  `json:"channel_code"`
	ChannelType int64   `json:"channel_type"`
	ChannelRate float64 `json:"channel_rate"`
	SingleFee   int64   `json:"single_fee"`
	Status      int64   `json:"status"`
}

type GetChannelNameListReq struct {
	ChannelType   int64 `form:"channel_type,optional"`
	ChannelStatus int64 `form:"channel_status,optional"`
}

type GetChannelNameListResponse struct {
	Total int64             `json:"total"`
	List  []ChannelNameList `json:"list"`
}

type ChannelNameList struct {
	ChannelId   int64  `json:"channel_id"`
	ChannelName string `json:"channel_name"`
}

type GetWalletInfoReply struct {
	Currency     string `json:"currency"`
	Balance      int64  `json:"balance"`
	FrozenAmount int64  `json:"frozen_amount"`
}

type GetBankCardListRequest struct {
	Page     int64  `form:"page"`
	PageSize int64  `form:"page_size"`
	Search   string `form:"search,optional"`
}

type GetBankCardListResponse struct {
	Total int64          `json:"total"`
	List  []BankCardList `json:"list"`
}

type BankCardList struct {
	CardId      int64  `json:"card_id"`
	BankName    string `json:"bank_name"`
	AccountName string `json:"account_name"`
	CardNumber  string `json:"card_number"`
	BranchName  string `json:"branch_name"`
	Currency    string `json:"currency"`
	Remark      string `json:"remark"`
	CreateTime  int64  `json:"create_time"`
	UpdateTime  int64  `json:"update_time"`
}

type AddBankCardRequest struct {
	BankName    string `json:"bank_name"`
	AccountName string `json:"account_name"`
	CardNumber  string `json:"card_number"`
	BranchName  string `json:"branch_name,optional"`
	Remark      string `json:"remark,optional"`
}

type AddBankCardResponse struct {
	CardId int64 `json:"card_id"`
}

type UpdateBankCardRequest struct {
	CardId      int64  `json:"card_id"`
	BankName    string `json:"bank_name,optional"`
	AccountName string `json:"account_name,optional"`
	CardNumber  string `json:"card_number,optional"`
	BranchName  string `json:"branch_name"`
	Remark      string `json:"remark"`
}

type DeleteBankCardRequest struct {
	CardId int64 `json:"card_id"`
}

type GetWalletLogListReq struct {
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
	IdOrBusinessNo  string `form:"id_or_business_no,optional"`
	OpType          int64  `form:"op_type,optional"`
	OrderType       int64  `form:"order_type,optional"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
}

type GetWalletLogListReply struct {
	List  []WalletLogList `json:"list"`
	Total int64           `json:"total"`
}

type WalletLogList struct {
	Id           int64  `json:"id"`
	CreateTime   int64  `json:"create_time"`   //创建时间
	OpType       int64  `json:"op_type"`       //变动类型：1+，2-
	ChangeAmount int64  `json:"change_amount"` //变动金额
	AfterBalance int64  `json:"after_balance"` //变动后余额
	BusinessNo   string `json:"business_no"`   //业务单号:(充值；提现；代付；收款)
	OrderType    int64  `json:"order_type"`    //变动来源：1-手动调账；2-充值；3-提现；4-代付；5-收款；
	Remark       string `json:"remark"`        //备注
}

type RechargeReq struct {
	BankCardId int64  `json:"bank_card_id"`
	Amount     int64  `json:"amount"`
	Remark     string `json:"remark,optional"`
}

type RechargeReply struct {
}

type PlatformBankCardListReq struct {
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

type PlatformBankCardListReply struct {
	List  []PlatformBankCardList `json:"list"`
	Total int64                  `json:"total"`
}

type PlatformBankCardList struct {
	Id          int64  `json:"id"`
	BankName    string `json:"bank_name"`    //	银行名称
	AccountName string `json:"account_name"` //	开户名
	CardNumber  string `json:"card_number"`  //	银行卡号
	BranchName  string `json:"branch_name"`  //	银行卡号
	Currency    string `json:"currency"`     //	币种
	MaxAmount   int64  `json:"max_amount"`   //	最大收款额度
	QrCode      string `json:"qr_code"`      //	收款二维码
}

type RechargeOrderListRequest struct {
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	OrderNo         string `form:"order_no,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
}

type RechargeOrderListResponse struct {
	Total int64               `json:"total"`
	List  []RechargeOrderList `json:"list"`
}

type RechargeOrderList struct {
	OrderNo     string `json:"order_no"`
	OrderAmount int64  `json:"order_amount"`
	BankName    string `json:"bank_name"`
	PayeeName   string `json:"payee_name"`
	CardNumber  string `json:"card_number"`
	BranchName  string `json:"branch_name"`
	OrderStatus int64  `json:"order_status"`
	AuditRemark string `json:"audit_remark"`
	CreateTime  int64  `json:"create_time"`
	UpdateTime  int64  `json:"update_time"`
	Currency    string `json:"currency"`
	Remark      string `json:"remark"` //充值备注
}

type GetWithdrawConfigResponse struct {
	Config WithdrawConfig `form:"config"`
}

type WithdrawConfig struct {
	SingleMinAmount int64   `json:"single_min_amount"`
	SingleMaxAmount int64   `json:"single_max_amount"`
	DeductionMethod int64   `json:"deduction_method"`
	Rate            float64 `json:"rate"`
	SingleFee       int64   `json:"single_fee"`
}

type WithdrawRequest struct {
	Amount      int64  `json:"amount"`
	Remark      string `json:"remark,optional"`
	PayPassword string `json:"pay_password"`
	TotpCode    string `json:"totp_code"`
	BankName    string `json:"bank_name"`            //银行名称
	BranchName  string `json:"branch_name,optional"` //银行支行名称
	PayeeName   string `json:"payee_name"`           //收款人
	CardNumber  string `json:"card_number"`          //卡号
	BankCode    string `json:"bank_code,optional"`   //银行代码
}

type WithdrawOrderListRequest struct {
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
	OrderNo         string `form:"order_no,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
}

type WithdrawOrderListResponse struct {
	Total int64               `json:"total"`
	List  []WithdrawOrderList `json:"list"`
}

type WithdrawOrderList struct {
	OrderNo     string `json:"order_no"`
	OrderStatus int64  `json:"order_status"`
	OrderAmount int64  `json:"order_amount"`
	Fee         int64  `json:"fee"`
	RealAmount  int64  `json:"real_amount"`
	BankName    string `json:"bank_name"`
	PayeeNmae   string `json:"payee_nmae"`
	CardNumber  string `json:"card_number"`
	BranchName  string `json:"branch_name"`
	AuditRemark string `json:"audit_remark"`
	AuditTime   int64  `json:"audit_time"`
	CreateTime  int64  `json:"create_time"`
	Currency    string `json:"currency"`
	Remark      string `json:"remark"`
}

type HomeInfoResponse struct {
	OrderNumber        int64         `json:"order_number"`         //今日收款总订单数
	SuccessOrderNumber int64         `json:"success_order_number"` //今日收款成功订单数
	SuccessAmount      int64         `json:"success_amount"`       //今日成功收款金额
	ReceiveList        []ReceiveData `json:"receive_list"`         //收款统计数据
}

type ReceiveData struct {
	CreateTime int64 `json:"create_time"` //创建时间
	Amount     int64 `json:"amount"`      //收款金额
}

type TransferSingleReq struct {
	ChannelId      int64  `json:"channel_id"`
	BankName       string `json:"bank_name"`
	AccountName    string `json:"account_name"`
	CardNumbers    string `json:"card_numbers"`
	BankCode       string `json:"bank_code,optional"`
	BankBranchName string `json:"bank_branch_name,optional"`
	ReqAmount      int64  `json:"req_amount"`
	PayPassword    string `json:"pay_password"`
	Remark         string `json:"remark,optional"`
	TotpCode       string `json:"totp_code"`
}

type PayOrderListRequest struct {
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	OrderNo         string `form:"order_no,optional"`
	MerchantOrderNo string `form:"merchant_order_no,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
	ChannelId       int64  `form:"channel_id,optional"`
	ChannelName     string `form:"channel_name,optional"`
	OrderType       string `form:"order_type,optional"`
}

type PayOrderListResponse struct {
	Total int64          `json:"total"`
	List  []PayOrderList `json:"list"`
}

type PayOrderList struct {
	OrderNo         string `json:"order_no"`
	MerchantOrderNo string `json:"merchant_order_no"`
	OrderAmount     int64  `json:"order_amount"`
	Fee             int64  `json:"fee"`
	IncreaseAmount  int64  `json:"increase_amount"`
	ChannelName     string `json:"channel_name"`
	OrderStatus     int64  `json:"order_status"`
	CreateTime      int64  `json:"create_time"`
	UpdateTime      int64  `json:"update_time"`
	PaymentAmount   int64  `json:"payment_amount"` // 用户实际支付金额
}

type TransferManualOrderListRequest struct {
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	OrderNo         string `form:"order_no,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
}

type TransferManualOrderListReply struct {
	Total int64                     `json:"total"`
	List  []TransferManualOrderList `json:"list"`
}

type TransferManualOrderList struct {
	OrderNo         string `json:"order_no"`          //平台订单号
	Currency        string `json:"currency"`          //币种
	OrderAmount     int64  `json:"order_amount"`      //订单请求金额
	MerchantFee     int64  `json:"merchant_fee"`      //商户手续费
	PayeeRealAmount int64  `json:"payee_real_amount"` //收款人到账金额
	BankName        string `json:"bank_name"`         //收款银行
	AccountName     string `json:"account_name"`      //收款人姓名
	CardNumber      string `json:"card_number"`       //收款卡号
	BranchName      string `json:"branch_name"`       //支行名称
	OrderStatus     int64  `json:"order_status"`      //订单状态: 1-待支付; 2-支付成功; 3-支付失败
	CreateTime      int64  `json:"create_time"`       //创建时间
	UpdateTime      int64  `json:"update_time"`       //更新时间
	OrderSource     int64  `json:"order_source"`      // 订单来源：1-接口; 2-平台提现派单；3-商户后台付款
	ChannelName     string `json:"channel_name"`      // 通道名称
	Remark          string `json:"remark"`            // 付款备注
}

type TransferInterfaceOrderListRequest struct {
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	OrderNo         string `form:"order_no,optional"`
	MerchantOrderNo string `form:"merchant_order_no,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
	OrderType       string `form:"order_type,optional"`
}

type TransferInterfaceOrderListReply struct {
	Total int64                        `json:"total"`
	List  []TransferInterfaceOrderList `json:"list"`
}

type TransferInterfaceOrderList struct {
	OrderNo             string `json:"order_no"`              // 平台订单号
	MerchantOrderNo     string `json:"merchant_order_no"`     // 商户订单号
	Currency            string `json:"currency"`              // 币种
	OrderAmount         int64  `json:"order_amount"`          // 订单请求金额
	MerchantFee         int64  `json:"merchant_fee"`          // 商户手续费
	PayeeRealAmount     int64  `json:"payee_real_amount"`     // 收款人到账金额
	PlatformChannelName string `json:"platform_channel_name"` // 平台通道
	OrderStatus         int64  `json:"order_status"`          // 订单状态: 1-待支付; 2-支付成功; 3-支付失败
	CreateTime          int64  `json:"create_time"`           // 创建时间
	UpdateTime          int64  `json:"update_time"`           // 更新时间
	OrderSource         int64  `json:"order_source"`          // 订单来源：1-接口; 2-平台提现派单；3-商户后台付款
	Remark              string `json:"remark"`                // 更新时间
}

type TransferOrderDetailRequest struct {
	OrderNo string `form:"order_no"`
}

type TransferOrderDetailReply struct {
	Data TransferOrderDetailDetail `json:"data"`
}

type TransferOrderDetailDetail struct {
	OrderNo         string `json:"order_no"`          //平台订单号
	MerchantOrderNo string `json:"merchant_order_no"` //商户订单号
	Currency        string `json:"currency"`          //币种
	OrderAmount     int64  `json:"order_amount"`      //订单请求金额
	MerchantFee     int64  `json:"merchant_fee"`      //商户手续费
	DecreaseAmount  int64  `json:"decrease_amount"`   //账户扣除的金额
	FeeDeductType   int64  `json:"fee_deduct_type"`   //手续费扣款方式(1内扣,2外扣)
	PayeeRealAmount int64  `json:"payee_real_amount"` //收款人到账金额
	CreateTime      int64  `json:"create_time"`       //创建时间
	UpdateTime      int64  `json:"update_time"`       //更新时间
	BankName        string `json:"bank_name"`         //收款银行名称
	AccountName     string `json:"account_name"`      //银行卡开户名
	CardNumber      string `json:"card_number"`       //收款卡号
	BranchName      string `json:"branch_name"`       //支行名称
	OrderSource     int64  `json:"order_source"`      // 订单来源
	ChannelName     string `json:"channel_name"`      // 通道名称
}

type ModifyPayTestOrderStatusRequest struct {
	OrderNo     string `json:"order_no"`
	OrderStatus int64  `json:"order_status"`
}

type ModifyTransferTestOrderStatusRequest struct {
	OrderNo     string `json:"order_no"`
	OrderStatus int64  `json:"order_status"`
}

type PayOrderNotifyRequest struct {
	OrderNo string `json:"order_no"`
}

type PayOrderNotifyResponse struct {
	NotifyResponse string `json:"notify_response"`
}

type TransferOrderNotifyRequest struct {
	OrderNo string `json:"order_no"`
}

type TransferOrderNotifyResponse struct {
	NotifyResponse string `json:"notify_response"`
}

type WalletLogExportRequest struct {
	IdOrBusinessNo  string `form:"id_or_business_no,optional"`
	OpType          int64  `form:"op_type,optional"`
	OrderType       int64  `form:"order_type,optional"`
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
}

type WalletLogExportResponse struct {
	Total           int64                 `json:"total"`
	IsDivideHundred bool                  `json:"is_divide_hundred"`
	List            []WalletLogExportData `json:"list"`
}

type WalletLogExportData struct {
	Id           int64  `json:"id"`
	BusinessNo   string `json:"business_no"`   //业务单号:(充值；提现；代付；收款)
	ChangeAmount int64  `json:"change_amount"` //变动金额
	AfterBalance int64  `json:"after_balance"` //变动后余额
	OpType       string `json:"op_type"`       //变动类型：1+，2-
	OrderType    string `json:"order_type"`    //变动来源：1-手动调账；2-充值；3-提现；4-代付；5-收款；
	Remark       string `json:"remark"`        //备注
	CreateTime   int64  `json:"create_time"`   //创建时间
}

type PayOrderExportRequest struct {
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	OrderNo         string `form:"order_no,optional"`
	MerchantOrderNo string `form:"merchant_order_no,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
	ChannelId       int64  `form:"channel_id,optional"`
	ChannelName     string `form:"channel_name,optional"`
}

type PayOrderExportResponse struct {
	Total               int64                `json:"total"`
	TotalReqAmount      int64                `json:"total_req_amount"`
	TotalPayAmount      int64                `json:"total_pay_amount"`
	TotalFee            int64                `json:"total_fee"`
	TotalIncreaseAmount int64                `json:"total_increase_amount"`
	IsDivideHundred     bool                 `json:"is_divide_hundred"`
	List                []PayOrderExportData `json:"list"`
}

type PayOrderExportData struct {
	Id              int64   `json:"id"`
	MerchantName    string  `json:"merchant_name"`
	OrderNo         string  `json:"order_no"`
	MerchantOrderNo string  `json:"merchant_order_no"`
	ReqAmount       int64   `json:"req_amount"`
	PaymentAmount   int64   `json:"payment_amount"`
	Rate            float64 `json:"rate"`
	SingleFee       int64   `json:"single_fee"`
	Fee             int64   `json:"fee"`
	IncreaseAmount  int64   `json:"increase_amount"`
	ChannelName     string  `json:"channel_name"`
	OrderStatus     string  `json:"order_status"`
	CreateTime      int64   `json:"create_time"`
	UpdateTime      int64   `json:"update_time"`
}

type TransferOrderExportRequest struct {
	StartCreateTime int64  `form:"start_create_time,optional"`
	EndCreateTime   int64  `form:"end_create_time,optional"`
	OrderNo         string `form:"order_no,optional"`
	MerchantOrderNo string `form:"merchant_order_no,optional"`
	OrderStatus     int64  `form:"order_status,optional"`
}

type TransferOrderExportResponse struct {
	Total               int64                     `json:"total"`
	TotalReqAmount      int64                     `json:"total_req_amount"`
	TotalFee            int64                     `json:"total_fee"`
	TotalIncreaseAmount int64                     `json:"total_increase_amount"`
	IsDivideHundred     bool                      `json:"is_divide_hundred"`
	List                []TransferOrderExportData `json:"list"`
}

type TransferOrderExportData struct {
	Id              int64   `json:"id"`
	MerchantName    string  `json:"merchant_name"`
	OrderNo         string  `json:"order_no"`
	MerchantOrderNo string  `json:"merchant_order_no"`
	ReqAmount       int64   `json:"req_amount"`
	Rate            float64 `json:"rate"`
	SingleFee       int64   `json:"single_fee"`
	Fee             int64   `json:"fee"`
	IncreaseAmount  int64   `json:"increase_amount"`
	ChannelName     string  `json:"channel_name"`
	OrderStatus     string  `json:"order_status"`
	CreateTime      int64   `json:"create_time"`
	UpdateTime      int64   `json:"update_time"`
}

type UploadFileReply struct {
	FileName string `json:"file_name"`
}

type IdentifyBatchTransferFileRequest struct {
	FileName string `json:"file_name"`
}

type IdentifyBatchTransferFileReply struct {
	BatchNo string `json:"batch_no"`
}

type ConfirmBatchTransferRequest struct {
	BatchNo     string `json:"batch_no"`
	PayPassword string `json:"pay_password"`
	TotpCode    string `json:"totp_code"`
}
