// Code generated by goctl. DO NOT EDIT.
package types

type RequestCommonField struct {
	MerchantNo string `json:"merchant_no"`
	Timestamp  int64  `json:"timestamp"`
}

type PayReq struct {
	RequestCommonField
	Subject    string `json:"subject"`      // 商品的标题/交易标题/订单标题/订单关键字等
	Amount     int64  `json:"amount"`       // 订单金额
	Currency   string `json:"currency"`     // 币种
	MchOrderNo string `json:"mch_order_no"` // 外部订单号(商户系统内部的订单号)
	TradeType  string `json:"trade_type"`   // 交易类型
	NotifyUrl  string `json:"notify_url"`   // 异步通知地址
	ReturnUrl  string `json:"return_url"`   // 同步跳转地址
	Attach     string `json:"attach"`       // 原样返回字段
}

type PayReply struct {
	MchOrderNo string `json:"mch_order_no"` // 外部订单号(商户系统内部的订单号)
	OrderNo    string `json:"order_no"`     // 平台订单号
	PayUrl     string `json:"pay_url"`      // 付款收银台地址
}

type PayOrderQueryReq struct {
	RequestCommonField
	MchOrderNo string `json:"mch_order_no"` // 外部订单号(商户系统内部的订单号)
	OrderNo    string `json:"order_no"`     // 平台订单号
}

type PayOrderQueryReply struct {
	MchOrderNo    string `json:"mch_order_no"`   // 外部订单号(商户系统内部的订单号)
	OrderNo       string `json:"order_no"`       // 平台订单号
	Amount        int64  `json:"amount"`         // 订单请求金额(即将废弃)
	ReqAmount     int64  `json:"req_amount"`     // 订单请求金额
	PaymentAmount int64  `json:"payment_amount"` // 实际支付金额
	Status        int64  `json:"status"`         // 订单状态
	Currency      string `json:"currency"`       // 币种
}

type TransferReq struct {
	RequestCommonField
	Amount             int64  `json:"amount"`                    // 订单金额
	Currency           string `json:"currency"`                  // 币种
	MchOrderNo         string `json:"mch_order_no"`              // 外部订单号(商户系统内部的订单号)
	TradeType          string `json:"trade_type"`                // 交易类型
	NotifyUrl          string `json:"notify_url"`                // 异步通知地址
	ReturnUrl          string `json:"return_url,optional"`       // 同步跳转地址
	Attach             string `json:"attach,optional"`           // 原样返回字段
	BankName           string `json:"bank_name"`                 // 收款银行名称
	BankCardHolderName string `json:"bank_card_holder_name"`     // 银行卡持卡人姓名
	BankCardNo         string `json:"bank_card_no"`              // 银行卡号
	BankBranchName     string `json:"bank_branch_name,optional"` // 收款银行支行名称
	BankCode           string `json:"bank_code,optional"`        // 银行代码
	Remark             string `json:"remark,optional"`           // 付款备注
}

type TransferReply struct {
	MchOrderNo string `json:"mch_order_no"` // 外部订单号(商户系统内部的订单号)
	OrderNo    string `json:"order_no"`     // 平台订单号
	Status     int64  `json:"status"`       // 订单状态
}

type SystemTransferReq struct {
	RequestCommonField
	Amount             int64  `json:"amount"`                    // 订单金额
	Currency           string `json:"currency"`                  // 币种
	MchOrderNo         string `json:"mch_order_no"`              // 外部订单号(商户系统内部的订单号)
	TradeType          string `json:"trade_type"`                // 交易类型
	BankName           string `json:"bank_name"`                 // 收款银行名称
	BankCardHolderName string `json:"bank_card_holder_name"`     // 银行卡持卡人姓名
	BankCardNo         string `json:"bank_card_no"`              // 银行卡号
	BankCode           string `json:"bankCode,optional"`         // 银行代码
	BankBranchName     string `json:"bank_branch_name,optional"` // 收款银行支行名称
	OrderSource        int64  `json:"order_source"`              // 订单来源
	Remark             string `json:"remark,optional"`           // 付款备注
}

type SystemTransferReply struct {
	MchOrderNo string `json:"mch_order_no"` // 外部订单号(商户系统内部的订单号)
	OrderNo    string `json:"order_no"`     // 平台订单号
	Status     int64  `json:"status"`       // 订单状态
}

type SystemTransferBatchReq struct {
	RequestCommonField
	BatchNo string `json:"batch_no"`
}

type SystemTransferBatchReply struct {
}

type TransferOrderQueryReq struct {
	RequestCommonField
	OrderNo    string `json:"order_no,optional"`     // 平台订单号
	MchOrderNo string `json:"mch_order_no,optional"` // 外部订单号(商户系统内部的订单号)
}

type TransferOrderQueryReply struct {
	MchOrderNo string `json:"mch_order_no"` // 外部订单号(商户系统内部的订单号)
	OrderNo    string `json:"order_no"`     // 平台订单号
	Amount     int64  `json:"amount"`       // 订单请求金额(即将废弃)
	ReqAmount  int64  `json:"req_amount"`   // 订单请求金额
	Status     int64  `json:"status"`       // 订单状态
	Currency   string `json:"currency"`     // 币种
}

type QueryBalanceReq struct {
	RequestCommonField
}

type QueryBalanceReply struct {
	Balance  int64  `json:"balance"`
	Currency string `json:"currency"`
}

type GetUnionpayReq struct {
}

type GetUnionpayReply struct {
	Url string `json:"url"`
}

type GetStaticReq struct {
	Path     string `path:"path"`
	Filename string `path:"filename"`
}

type GetStaticReply struct {
	ContentType string `json:"content_type"`
	Content     []byte `json:"content"`
}

type RequestCommonFieldT struct {
	MerchantNo string `json:"merchant_no"`
	Timestamp  int64  `json:"timestamp"`
}

type PayTestReq struct {
	RequestCommonFieldT
	Subject    string `json:"subject"`      // 商品的标题/交易标题/订单标题/订单关键字等
	Amount     int64  `json:"amount"`       // 订单金额
	Currency   string `json:"currency"`     // 币种
	MchOrderNo string `json:"mch_order_no"` // 外部订单号(商户系统内部的订单号)
	TradeType  string `json:"trade_type"`   // 交易类型
	NotifyUrl  string `json:"notify_url"`   // 异步通知地址
	ReturnUrl  string `json:"return_url"`   // 同步跳转地址
	Attach     string `json:"attach"`       // 原样返回字段
}

type PayTestReply struct {
	MchOrderNo string `json:"mch_order_no"` // 外部订单号(商户系统内部的订单号)
	OrderNo    string `json:"order_no"`     // 平台订单号
	PayUrl     string `json:"pay_url"`      // 付款收银台地址
}

type TransferTestReq struct {
	RequestCommonFieldT
	Amount             int64  `json:"amount"`                    // 订单金额
	Currency           string `json:"currency"`                  // 币种
	MchOrderNo         string `json:"mch_order_no"`              // 外部订单号(商户系统内部的订单号)
	TradeType          string `json:"trade_type"`                // 交易类型
	NotifyUrl          string `json:"notify_url"`                // 异步通知地址
	ReturnUrl          string `json:"return_url,optional"`       // 同步跳转地址
	Attach             string `json:"attach,optional"`           // 原样返回字段
	BankName           string `json:"bank_name"`                 // 收款银行名称
	BankCardHolderName string `json:"bank_card_holder_name"`     // 银行卡持卡人姓名
	BankCardNo         string `json:"bank_card_no"`              // 银行卡号
	BankBranchName     string `json:"bank_branch_name,optional"` // 收款银行支行名称
	BankCode           string `json:"bankCode,optional"`         // 银行代码
	Remark             string `json:"remark,optional"`           // 付款备注
}

type TransferTestReply struct {
	MchOrderNo string `json:"mch_order_no"` // 外部订单号(商户系统内部的订单号)
	OrderNo    string `json:"order_no"`     // 平台订单号
	Status     int64  `json:"status"`       // 订单状态
}

type SystemTransferTestReq struct {
	RequestCommonFieldT
	Amount             int64  `json:"amount"`                    // 订单金额
	Currency           string `json:"currency"`                  // 币种
	MchOrderNo         string `json:"mch_order_no"`              // 外部订单号(商户系统内部的订单号)
	TradeType          string `json:"trade_type"`                // 交易类型
	BankName           string `json:"bank_name"`                 // 收款银行名称
	BankCardHolderName string `json:"bank_card_holder_name"`     // 银行卡持卡人姓名
	BankCardNo         string `json:"bank_card_no"`              // 银行卡号
	BankCode           string `json:"bankCode,optional"`         // 银行代码
	BankBranchName     string `json:"bank_branch_name,optional"` // 收款银行支行名称
	OrderSource        int64  `json:"order_source"`              // 订单来源
	Remark             string `json:"remark,optional"`           // 付款备注
}

type SystemTransferTestReply struct {
	MchOrderNo string `json:"mch_order_no"` // 外部订单号(商户系统内部的订单号)
	OrderNo    string `json:"order_no"`     // 平台订单号
	Status     int64  `json:"status"`       // 订单状态
}
